metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml  # Metricbeat 모듈 설정 파일의 위치 지정
  reload.enabled: false  # 구성 파일의 변경 사항이 자동으로 리로드되는 것을 비활성화

metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: true  # X-Pack 모니터링을 활성화하여 보다 상세한 메트릭을 수집
    period: 10s  # 수집 주기 설정 (10초마다 메트릭 수집)
    hosts: ${ELASTIC_HOSTS}  # Elasticsearch 호스트 주소
    ssl.certificate_authorities: "certs/ca/ca.crt"  # CA 인증서 경로
    ssl.certificate: "certs/es01/es01.crt"  # SSL 인증서 경로
    ssl.key: "certs/es01/es01.key"  # SSL 키 파일 경로
    username: ${ELASTIC_USER}  # Elasticsearch 접속 계정
    password: ${ELASTIC_PASSWORD}  # Elasticsearch 접속 비밀번호
    ssl.enabled: true  # SSL 보안 연결 활성화

  - module: logstash
    xpack.enabled: true  # X-Pack 모니터링을 활성화
    period: 10s  # 수집 주기 설정
    hosts: ${LOGSTASH_HOSTS}  # Logstash 호스트 주소

  - module: kibana
    metricsets:
      - stats  # 수집할 메트릭 세트 지정
    period: 10s  # 수집 주기 설정
    hosts: ${KIBANA_HOSTS}  # Kibana 호스트 주소
    username: ${ELASTIC_USER}  # Kibana 접속 계정
    password: ${ELASTIC_PASSWORD}  # Kibana 접속 비밀번호
    xpack.enabled: true  # X-Pack 모니터링을 활성화

  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      #- "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]  # Docker 소켓 파일 경로
    period: 10s  # 수집 주기 설정
    enabled: true  # 이 모듈을 활성화

processors:
  - add_host_metadata: ~  # 호스트 메타데이터를 이벤트에 추가
  - add_docker_metadata: ~  # Docker 메타데이터를 이벤트에 추가

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}  # 출력 대상 Elasticsearch 호스트 주소
  username: ${ELASTIC_USER}  # Elasticsearch 접속 계정
  password: ${ELASTIC_PASSWORD}  # Elasticsearch 접속 비밀번호
  ssl:
    certificate: "certs/es01/es01.crt"  # SSL 인증서 파일
    certificate_authorities: "certs/ca/ca.crt"  # CA 인증서 경로
    key: "certs/es01/es01.key"  # SSL 키 파일
